### ISSUE TITLE
Sugestão: Anexar exceção de temporização na Atividade de Loop "Monitorar e participar certame até que haja vencedores"

### ISSUE THREAD

**Issue by glandre** [lppedro/mpn-group-2#2]
A atividade de loop está corretamente utilizada. Contudo, faço duas sugestões:
1. A condição de corrida poderia ser melhorada: "Enquanto não houver vencedores" ou "Até que haja vencedores";
2. Do jeito que o processo está modelado, me parece que pode haver um livelock aí... Provavelmente, a organização tem algum procedimento que deve ser seguido caso várias interações desse "certame" sejam realizadas sem que haja vencedores... Minha sugestão é anexar na borda da atividade uma exceção de temporização ("Timeout") para tratar esse detalhe.

**Comment by heliohfs** [comment]
Modificações aplicadas.

**Comment by glandre** [comment]
OK!
